In [1]:
!git clone https://github.com/graykode/seq2seq-dataloader
%cd seq2seq-dataloader

Cloning into 'seq2seq-dataloader'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 32 (delta 0), reused 1 (delta 0), pack-reused 29
Unpacking objects: 100% (32/32), done.
/content/seq2seq-dataloader


In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [0]:
import json
from data_loader import get_loader

In [0]:
# load word2id dictionaries
with open('./data/src_word2id.json', 'r') as f:
    src_word2id = json.load(f)
with open('./data/trg_word2id.json', 'r') as f:
    trg_word2id = json.load(f)

In [0]:
data_loader = get_loader(src_path='./data/src_train.txt',
                         trg_path='./data/trg_train.txt',
                         src_word2id=src_word2id,
                         trg_word2id=trg_word2id)

data_iter = iter(data_loader)
src_seqs, src_lengths, trg_seqs, trg_lengths, target, target_lengths = next(data_iter)

In [9]:
# src_seqs is a tensor of shape (batch_size, seq_length)
# seq_length is the maximum length of sequences in mini-batch data
print(src_seqs)
print(src_seqs.shape)

tensor([[ 994,   11, 1340,  ...,   24,  465,   38],
        [  63,  476,  544,  ...,  243,   38,    0],
        [ 188,    5,  237,  ..., 1193,   38,    0],
        ...,
        [ 747,    3,   13,  ...,    0,    0,    0],
        [ 299,    5,  143,  ...,    0,    0,    0],
        [ 491,  963,    4,  ...,    0,    0,    0]])
torch.Size([100, 49])


In [7]:
# '3' is UNK Token.
print(src_seqs[0])
print(src_lengths[0])

tensor([ 994,   11, 1340,   16,   17,   18,   19, 2242,   55, 4950, 4580, 1315,
           9,    4, 2625,   59,  855, 1700,    9, 4774,   24,    3, 2057,   59,
         614, 1093, 2852, 2846, 2681,    9, 1407,  614,    3,  833,   24,  391,
        2655,    9,   24,   11, 4392,   24, 3724,   13,  614, 1910,   24,  465,
          38])
49


In [10]:
print(trg_seqs)
print(trg_seqs.shape)

tensor([[   1,   49, 2267,  ...,    0,    0,    0],
        [   1,   41,  440,  ...,    0,    0,    0],
        [   1, 3700, 4919,  ...,    0,    0,    0],
        ...,
        [   1,   50, 1218,  ...,    0,    0,    0],
        [   1,  334,   18,  ...,    0,    0,    0],
        [   1,  385,  566,  ...,    0,    0,    0]])
torch.Size([100, 49])


In [12]:
# This is important!.
print(trg_seqs[0])
print(target[0])

tensor([   1,   49, 2267,    3, 4091,   68,    3, 2651,  152,  419,    8,  331,
         229,  524, 1680,  212,   49,  299, 1235,  156,  944, 3192,   14,  357,
        2454,  117,   23, 4624,   14,   50, 3648, 1819,    3,   14,  317,  171,
           3,    8,    3,   14,    3, 2676,  127, 1207,   28,    0,    0,    0,
           0])
tensor([  49, 2267,    3, 4091,   68,    3, 2651,  152,  419,    8,  331,  229,
         524, 1680,  212,   49,  299, 1235,  156,  944, 3192,   14,  357, 2454,
         117,   23, 4624,   14,   50, 3648, 1819,    3,   14,  317,  171,    3,
           8,    3,   14,    3, 2676,  127, 1207,   28,    2,    0,    0,    0,
           0])
